### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by littleweb** [btmorex/hapi-server-session#12]
file：hapi-server-session/lib/index.js
line：75

error：
 Debug: internal, implementation, error
     TypeError: Cannot read property 'sid' of null
     at loadSession (/node_modules/hapi-server-session/lib/index.js:75:36)
     at module.exports.internals.Manager.execute (/node_modules/hapi/lib/toolkit.js:35:106)
     at Request._invoke (/node_modules/hapi/lib/request.js:293:55)
     at Request._lifecycle (/node_modules/hapi/lib/request.js:263:80)
     at Request._execute (/node_modules/hapi/lib/request.js:170:20)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:182:7)

fixed：
const sessionId = request.state?request.state[options.name]:"";

**Comment by btmorex** [comment]
That's odd. `request.state` should never be null when we're using it. Are you running this code in a strange environment or doing anything odd in terms of cookie parsing? Is it easily reproducible?
